~using AUTD3Sharp;
~using AUTD3Sharp.Link;
~using AUTD3Sharp.Utils;
~using var autd = new ControllerBuilder().AddDevice(new AUTD3(Vector3d.Zero)).Open(Nop.Builder());
var dev = autd.Geometry[0];
var idx = dev.Idx;
dev.Enable = false;
dev.SoundSpeed = 340e3;
dev.SetSoundSpeedFromTemp(15);
dev.Attenuation = 0;
var t = new Vector3d(1, 0, 0);
var r = new Quaterniond(0, 0, 0, 1);
dev.Translate(t);
dev.Rotate(r);
dev.Affine(t, r);
var wavelength = dev.Wavelength;
var wavenumber = dev.Wavenumber;