name: Document

on:
  push:
    branches:
      - 'main'

jobs:

  build:
    name: build-doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup mdbook
        uses: ./.github/actions/setup-mdbook
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build book
        run: |
          MDBOOK_BOOK__src=src/en mdbook build --dest-dir book/en
          MDBOOK_BOOK__src=src/jp mdbook build --dest-dir book/jp
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book
          force_orphan: true
